# ----------------------------------------------------------- #
# Note: this file originates in ahmadnassri/template-template #
# ----------------------------------------------------------- #

version: 2
updates:
  - package-ecosystem: gitsubmodule
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily

  - package-ecosystem: docker
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
