if: tag IS blank

language: node_js

services: docker

node_js:
  - 9
  - 8
  - 6

cache:
  directories:
    - node_modules

stages:
  - test
  - coverage
  - release

before_install: export PATH=$PATH:$TRAVIS_BUILD_DIR/.scripts

jobs:
  include:
    - stage: coverage
      node: 9
      before_script: test-reporter before-build
      script: npm run test:tap
      after_script: test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: release
      node: 9
      script: npx semantic-release
      if: branch = master
      if: type IN (push)
