name: commit-lint

on: [push, pull_request]

jobs:
  commit-lint:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-commit-lint@v1
        with:
          config: .github/linters/.commit-lint.yml
