name: readme

on:
  push:
    paths:
      - docs/**
      - colophon.yml
      - .github/workflows/readme.yml

jobs:
  readme:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --metadata-file=colophon.yml
            --template=docs/README.template
            --output=README.md
            --from=markdown_github+yaml_metadata_block
            --to=gfm
            --fail-if-warnings
            --wrap=preserve
            docs/README.md

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const { readFile } = require('fs/promises')

            const content = await readFile(`${process.env.GITHUB_WORKSPACE}/README.md`)

            await github.repos.createOrUpdateFileContents({
              ...context.repo,
              path: 'README.md',
              message: 'docs(readme): update readme',
              content: content.toString('base64')
            })
