name: test

on: [ push, pull_request ]

env:
  NODE_ENV: test

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2.1.2
      - uses: actions/checkout@v2
      - run: npm audit --audit-level=moderate

  test:
    needs: audit

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12, 13, 14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run test:ci
