name: test

on: [ push, pull_request ]

env:
  NODE_ENV: test

jobs:
  deduplicate:
    runs-on: ubuntu-latest

    # run on external PRs, but on internal PRs as they'll be run by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - run: echo "this is fine 🔥"

  audit:
    needs: deduplicate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2.1.2
      - uses: actions/checkout@v2
      - run: npm audit --audit-level=moderate

  test:
    needs: audit

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12, 13, 14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run test:ci
